services:
  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: oj-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}

  backend:
    image: ${BACKEND_IMAGE}
    container_name: oj-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - compiler
    env_file:
      - .env

  compiler:
    image: ${COMPILER_IMAGE}
    container_name: oj-compiler
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env