version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: oj-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_COMPILER_URL=http://localhost:5001

  backend:
    build:
      context: ./backend
    container_name: oj-backend
    ports:
      - "5000:5000"
    depends_on:
      - compiler
    env_file:
      - ./backend/.env

  compiler:
    build:
      context: ./compiler
    container_name: oj-compiler
    ports:
      - "5001:5001"
    env_file:
      - ./compiler/.env

networks:
  default:
    driver: bridge
