version: '3.8'

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: oj-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_COMPILER_URL=${VITE_COMPILER_URL}

  backend:
    image: ${BACKEND_IMAGE}
    container_name: oj-backend
    ports:
      - "5000:5000"
    depends_on:
      - oj-compiler  # This should match the service name below
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - COMPILER_SERVICE_URL=${COMPILER_SERVICE_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  oj-compiler:  # This is the service name that backend will use
    image: ${COMPILER_IMAGE}
    container_name: oj-compiler
    ports:
      - "5001:5001"
    environment:
      - PORT=5001

networks:
  default:
    driver: bridge